In [19]:
import requests
import pandas as pd
import numpy as np
import xml.etree.ElementTree as ET
import os
from dotenv import load_dotenv

In [20]:
# .env 파일 로드
load_dotenv()
# 1. API 요청 URL 및 파라미터 설정
url = 'http://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev'
# 본인의 발급받은 Decoding 키를 입력하세요.
service_key = os.getenv('DATA_GO_KR_API_KEY')

params = {
    'serviceKey':service_key,
    'pageNo':'1',
    'numOfRows':'100',
    'LAWD_CD':'11110',
    'DEAL_YMD':'202312'
}

# 2. API 요청 및 응답 확인
response = requests.get(url, params=params)
root = ET.fromstring(response.content)

# 3. XML 데이터를 데이터프레임으로 변환
data_list = []
rng = np.random.default_rng(seed=42)
# 선택할 지역 리스트 정의
locations = ['서울', '광주', '대전', '대구', '제주']

for item in root.findall('.//item'):
    data = {
        'Transaction_Date': item.find('dealYear').text + item.find('dealMonth').text + item.find('dealDay').text,
        'dealAmount': item.find('dealAmount').text if item.find('dealAmount') is not None else None,
        'excluUseAr': item.find('excluUseAr').text if item.find('excluUseAr') is not None else None,
        'floor': item.find('floor').text if item.find('floor') is not None else None,
        'buildYear': item.find('buildYear').text if item.find('buildYear') is not None else None,
        # rng.choice를 사용하여 리스트 중 하나를 무작위 선택
        'Location': rng.choice(locations) 
    }
    data_list.append(data)

df_api = pd.DataFrame(data_list)
df_api.to_csv('df_api.csv', encoding='utf-8-sig')
df_api

   Transaction_Date dealAmount excluUseAr floor buildYear Location
0          20231226    102,000     45.879    16      2017       서울
1          20231228    102,000     45.879    16      2017       대구
2          20231230     10,800      16.67     9      2012       대구
3          20231227    194,000    84.8359     8      2017       대전
4          20231222    128,000    59.6737     9      2019       대전
5          20231216    150,000    84.8792    14      2019       제주
6          20231228    114,000     236.07     2      2009       서울
7          20231220    118,000     110.53     4      2001       대구
8          20231211    280,000    118.749    16      2020       광주
9           2023128     69,000      79.87    11      1992       서울
10         20231223     23,900       44.4     6      1997       대전
11         20231226     16,000     18.505    12      2017       제주
12          2023124     10,500     17.811    11      2013       대구
13         20231217    148,000    59.7547     4      2017       대구
14         20231224     10,000      12.08    12      2013       대구
15          2023122     70,000      79.87    10      1992       대구
16          2023122    179,000     151.81    11      2008       대전
17         20231219     10,400      12.09     9      2013       서울
18          2023121     90,000      84.74     2      2007       제주
19          2023121     98,500    84.9478     9      2009       대전

In [11]:
response.content

b'<?xml version="1.0" encoding="utf-8" standalone="yes"?><response><header><resultCode>000</resultCode><resultMsg>OK</resultMsg></header><body><items><item><aptDong>402</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xec\x9e\x90\xec\x9d\xb4(4\xeb\x8b\xa8\xec\xa7\x80)</aptNm><aptSeq>11110-2464</aptSeq><bonbun>0126</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>102,000</dealAmount><dealDay>26</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>45.879</excluUseAr><floor>16</floor><jibun>126</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.08</rgstDate><roadNm>\xec\x86\xa1\xec\x9b\x94\xea\xb8\xb8</roadNm><roadNmBonbun>00155</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100192</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18000</umdCd><umdNm>\xea\xb5\x90\xeb\xb6\x81\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xec\x9e\x90\xec\x9d\xb4(4\xeb\x8b\xa8\xec\xa7\x80)</aptNm><aptSeq>11110-2464</aptSeq><bonbun>0126</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay>24.02.08</cdealDay><cdealType>O</cdealType><dealAmount>102,000</dealAmount><dealDay>28</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>45.879</excluUseAr><floor>16</floor><jibun>126</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><roadNm>\xec\x86\xa1\xec\x9b\x94\xea\xb8\xb8</roadNm><roadNmBonbun>00155</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100192</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18000</umdCd><umdNm>\xea\xb5\x90\xeb\xb6\x81\xeb\x8f\x99</umdNm></item><item><aptDong>1</aptDong><aptNm>\xec\x82\xbc\xec\xa0\x84\xec\x86\x94\xed\x95\x98\xec\x9e\x842\xec\xb0\xa8</aptNm><aptSeq>11110-2322</aptSeq><bonbun>0296</bonbun><bubun>0019</bubun><buildYear>2012</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,800</dealAmount><dealDay>30</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>16.67</excluUseAr><floor>9</floor><jibun>296-19</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.22</rgstDate><roadNm>\xec\xa2\x85\xeb\xa1\x9c58\xea\xb0\x80\xea\xb8\xb8</roadNm><roadNmBonbun>00027</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100358</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong>209</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xec\x9e\x90\xec\x9d\xb4(2\xeb\x8b\xa8\xec\xa7\x80)</aptNm><aptSeq>11110-2445</aptSeq><bonbun>0199</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>194,000</dealAmount><dealDay>27</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>84.8359</excluUseAr><floor>8</floor><jibun>199</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.15</rgstDate><roadNm>\xec\x86\xa1\xec\x9b\x94\xea\xb8\xb8</roadNm><roadNmBonbun>00099</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100192</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17900</umdCd><umdNm>\xed\x99\x8d\xed\x8c\x8c\xeb\x8f\x99</umdNm></item><item><aptDong>102\xeb\x8f\x99</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xeb\xa1\xaf\xeb\x8d\xb0\xec\xba\x90\xec\x8a\xac</aptNm><aptSeq>11110-2519</aptSeq><bonbun>0089</bonbun><bubun>0000</bubun><buildYear>2019</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>128,000</dealAmount><dealDay>22</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xea\xb2\xbd\xea\xb8\xb0 \xeb\xb6\x80\xec\xb2\x9c\xec\x9b\x90\xeb\xaf\xb8\xea\xb5\xac \xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>59.6737</excluUseAr><floor>9</floor><jibun>89</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.22</rgstDate><roadNm>\xed\x86\xb5\xec\x9d\xbc\xeb\xa1\x9c</roadNm><roadNmBonbun>00230</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3000008</roadNmCd><roadNmSeq>00</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18700</umdCd><umdNm>\xeb\xac\xb4\xec\x95\x85\xeb\x8f\x99</umdNm></item><item><aptDong>103\xeb\x8f\x99</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xeb\xa1\xaf\xeb\x8d\xb0\xec\xba\x90\xec\x8a\xac</aptNm><aptSeq>11110-2519</aptSeq><bonbun>0089</bonbun><bubun>0000</bubun><buildYear>2019</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>150,000</dealAmount><dealDay>16</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>84.8792</excluUseAr><floor>14</floor><jibun>89</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.03.05</rgstDate><roadNm>\xed\x86\xb5\xec\x9d\xbc\xeb\xa1\x9c</roadNm><roadNmBonbun>00230</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3000008</roadNmCd><roadNmSeq>00</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18700</umdCd><umdNm>\xeb\xac\xb4\xec\x95\x85\xeb\x8f\x99</umdNm></item><item><aptDong>\xec\x97\x98\xeb\xa6\xac\xec\x8b\x9c\xec\x95\x84</aptDong><aptNm>\xec\x97\x98\xeb\xa6\xac\xec\x8b\x9c\xec\x95\x84</aptNm><aptSeq>11110-2261</aptSeq><bonbun>0066</bonbun><bubun>0001</bubun><buildYear>2009</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>114,000</dealAmount><dealDay>28</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>236.07</excluUseAr><floor>2</floor><jibun>66-1</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.12</rgstDate><roadNm>\xed\x8f\x89\xec\xb0\xbd\xeb\xac\xb8\xed\x99\x94\xeb\xa1\x9c</roadNm><roadNmBonbun>00142</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3100023</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18300</umdCd><umdNm>\xed\x8f\x89\xec\xb0\xbd\xeb\x8f\x99</umdNm></item><item><aptDong>102</aptDong><aptNm>\xeb\xa1\xaf\xeb\x8d\xb0\xeb\x82\x99\xec\xb2\x9c\xeb\x8c\x80</aptNm><aptSeq>11110-71</aptSeq><bonbun>0072</bonbun><bubun>0000</bubun><buildYear>2001</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>118,000</dealAmount><dealDay>20</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>110.53</excluUseAr><floor>4</floor><jibun>72</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.29</rgstDate><roadNm>\xed\x8f\x89\xec\xb0\xbd\xeb\xac\xb8\xed\x99\x94\xeb\xa1\x9c</roadNm><roadNmBonbun>00140</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3100023</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18300</umdCd><umdNm>\xed\x8f\x89\xec\xb0\xbd\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xeb\x94\x94\xed\x8c\xb0\xeb\xa6\xac\xec\x8a\xa4</aptNm><aptSeq>11110-2539</aptSeq><bonbun>0171</bonbun><bubun>0000</bubun><buildYear>2020</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>280,000</dealAmount><dealDay>11</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\x84\xb1\xeb\x8f\x99\xea\xb5\xac</estateAgentSggNm><excluUseAr>118.749</excluUseAr><floor>16</floor><jibun>171</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.22</rgstDate><roadNm>\xec\x83\x88\xeb\xac\xb8\xec\x95\x88\xeb\xa1\x9c2\xea\xb8\xb8</roadNm><roadNmBonbun>00010</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100157</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>12100</umdCd><umdNm>\xec\x8b\xa0\xeb\xac\xb8\xeb\xa1\x9c2\xea\xb0\x80</umdNm></item><item><aptDong>102</aptDong><aptNm>\xec\xb0\xbd\xec\x8b\xa0\xec\x8c\x8d\xec\x9a\xa91</aptNm><aptSeq>11110-37</aptSeq><bonbun>0702</bonbun><bubun>0000</bubun><buildYear>1992</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>69,000</dealAmount><dealDay>8</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>79.87</excluUseAr><floor>11</floor><jibun>702</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.03.08</rgstDate><roadNm>\xeb\x8f\x99\xeb\xa7\x9d\xec\x82\xb0\xea\xb8\xb8</roadNm><roadNmBonbun>00019</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100065</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17400</umdCd><umdNm>\xec\xb0\xbd\xec\x8b\xa0\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xeb\x8f\x84\xec\x8b\x9c\xea\xb7\xb8\xeb\xa6\xb0\xeb\xb9\x8c\xeb\x9d\xbc</aptNm><aptSeq>11110-44</aptSeq><bonbun>0181</bonbun><bubun>0121</bubun><buildYear>1997</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>23,900</dealAmount><dealDay>23</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>44.4</excluUseAr><floor>6</floor><jibun>181-121</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.23</rgstDate><roadNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x991\xea\xb8\xb8</roadNm><roadNmBonbun>00031</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100200</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong>\xed\x8f\xac\xeb\xa0\x88\xec\x8a\xa4\xed\x8a\xb8\xed\x9e\x90\xec\x8b\x9c\xed\x8b\xb0</aptDong><aptNm>\xed\x8f\xac\xeb\xa0\x88\xec\x8a\xa4\xed\x8a\xb8\xed\x9e\x90\xec\x8b\x9c\xed\x8b\xb0</aptNm><aptSeq>11110-2440</aptSeq><bonbun>0065</bonbun><bubun>0002</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>16,000</dealAmount><dealDay>26</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>18.505</excluUseAr><floor>12</floor><jibun>65-2</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.05</rgstDate><roadNm>\xeb\x8c\x80\xed\x95\x99\xeb\xa1\x9c</roadNm><roadNmBonbun>00033</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3100002</roadNmCd><roadNmSeq>00</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>16200</umdCd><umdNm>\xed\x9a\xa8\xec\xa0\x9c\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xec\xa2\x85\xeb\xa1\x9c\xec\xa4\x91\xed\x9d\xa5S\xed\x81\xb4\xeb\x9e\x98\xec\x8a\xa4</aptNm><aptSeq>11110-2339</aptSeq><bonbun>0202</bonbun><bubun>0003</bubun><buildYear>2013</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,500</dealAmount><dealDay>4</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>17.811</excluUseAr><floor>11</floor><jibun>202-3</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.29</rgstDate><roadNm>\xec\xa2\x85\xeb\xa1\x9c66\xea\xb8\xb8</roadNm><roadNmBonbun>00028</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100372</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong>307</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xec\x9e\x90\xec\x9d\xb4(3\xeb\x8b\xa8\xec\xa7\x80)</aptNm><aptSeq>11110-2446</aptSeq><bonbun>0233</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>148,000</dealAmount><dealDay>17</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>59.7547</excluUseAr><floor>4</floor><jibun>233</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.26</rgstDate><roadNm>\xea\xb2\xbd\xea\xb5\x90\xec\x9e\xa5\xea\xb8\xb8</roadNm><roadNmBonbun>00035</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100002</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17700</umdCd><umdNm>\xed\x8f\x89\xeb\x8f\x99</umdNm></item><item><aptDong>1</aptDong><aptNm>\xec\xa2\x85\xeb\xa1\x9c\xec\x9c\xa0\xec\xbc\x80\xec\x9d\xb4201</aptNm><aptSeq>11110-2334</aptSeq><bonbun>0201</bonbun><bubun>0011</bubun><buildYear>2013</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,000</dealAmount><dealDay>24</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>12.08</excluUseAr><floor>12</floor><jibun>201-11</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.27</rgstDate><roadNm>\xeb\x82\x9c\xea\xb3\x84\xeb\xa1\x9c29\xea\xb8\xb8</roadNm><roadNmBonbun>00033</roadNmBonbun><roadNmBubun>00004</roadNmBubun><roadNmCd>4100030</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong>102</aptDong><aptNm>\xec\xb0\xbd\xec\x8b\xa0\xec\x8c\x8d\xec\x9a\xa91</aptNm><aptSeq>11110-37</aptSeq><bonbun>0702</bonbun><bubun>0000</bubun><buildYear>1992</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>70,000</dealAmount><dealDay>2</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>79.87</excluUseAr><floor>10</floor><jibun>702</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.12</rgstDate><roadNm>\xeb\x8f\x99\xeb\xa7\x9d\xec\x82\xb0\xea\xb8\xb8</roadNm><roadNmBonbun>00019</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100065</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17400</umdCd><umdNm>\xec\xb0\xbd\xec\x8b\xa0\xeb\x8f\x99</umdNm></item><item><aptDong>104</aptDong><aptNm>\xea\xb4\x91\xed\x99\x94\xeb\xac\xb8\xec\x8a\xa4\xed\x8e\x98\xec\x9d\xb4\xec\x8a\xa4\xeb\xb3\xb8(101\xeb\x8f\x99~105\xeb\x8f\x99)</aptNm><aptSeq>11110-2203</aptSeq><bonbun>0009</bonbun><bubun>0000</bubun><buildYear>2008</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>179,000</dealAmount><dealDay>2</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>151.81</excluUseAr><floor>11</floor><jibun>9</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.01</rgstDate><roadNm>\xec\x82\xac\xec\xa7\x81\xeb\xa1\x9c8\xea\xb8\xb8</roadNm><roadNmBonbun>00004</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100135</roadNmCd><roadNmSeq>03</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>11500</umdCd><umdNm>\xec\x82\xac\xec\xa7\x81\xeb\x8f\x99</umdNm></item><item><aptDong>1</aptDong><aptNm>\xec\xa2\x85\xeb\xa1\x9c\xec\x9c\xa0\xec\xbc\x80\xec\x9d\xb4201</aptNm><aptSeq>11110-2334</aptSeq><bonbun>0201</bonbun><bubun>0011</bubun><buildYear>2013</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,400</dealAmount><dealDay>19</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>12.09</excluUseAr><floor>9</floor><jibun>201-11</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.20</rgstDate><roadNm>\xeb\x82\x9c\xea\xb3\x84\xeb\xa1\x9c29\xea\xb8\xb8</roadNm><roadNmBonbun>00033</roadNmBonbun><roadNmBubun>00004</roadNmBubun><roadNmCd>4100030</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xeb\x91\x90\xeb\xa0\x88\xec\x97\x98\xeb\xa6\xac\xec\x8b\x9c\xec\x95\x88</aptNm><aptSeq>11110-2175</aptSeq><bonbun>0174</bonbun><bubun>0001</bubun><buildYear>2007</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>90,000</dealAmount><dealDay>1</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>84.74</excluUseAr><floor>2</floor><jibun>174-1</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.20</rgstDate><roadNm>\xed\x95\x84\xec\x9a\xb4\xeb\x8c\x80\xeb\xa1\x9c2\xea\xb8\xb8</roadNm><roadNmBonbun>00002</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100525</roadNmCd><roadNmSeq>03</roadNmSeq><roadNmSggCd>11110</road

In [ ]:
# import pandas as pd
# import xml.etree.ElementTree as ET

# # 1. response.content 또는 제공된 문자열 데이터를 사용합니다.
# # response = requests.get(url, params=params)
# # xml_data = response.content

# # 여기서는 예시를 위해 직접 데이터를 변환합니다.
# xml_data = response.content  

# # 2. XML 파싱
# root = ET.fromstring(xml_data)

# # 3. <item> 태그 내의 데이터를 추출하여 리스트에 담기
# items_list = []
# for item in root.findall('.//item'):
#     item_dict = {}
#     for child in item:
#         item_dict[child.tag] = child.text
#     items_list.append(item_dict)

# # 4. 데이터프레임 생성
# df = pd.DataFrame(items_list)

# # 데이터 확인
# print(f"총 {len(df)}건의 데이터가 변환되었습니다.")
# display(df.head())

In [ ]:
df.to_csv('APT_Feature.csv', encoding='utf-8-sig')

In [11]:
df_api.to_csv('df_api.csv', encoding='utf-8-sig')

In [3]:
print(ET.tostring(root, encoding='utf-8').decode('utf-8'))

<response><header><resultCode>000</resultCode><resultMsg>OK</resultMsg></header><body><items><item><aptDong>402</aptDong><aptNm>경희궁자이(4단지)</aptNm><aptSeq>11110-2464</aptSeq><bonbun>0126</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>102,000</dealAmount><dealDay>26</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>45.879</excluUseAr><floor>16</floor><jibun>126</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.08</rgstDate><roadNm>송월길</roadNm><roadNmBonbun>00155</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100192</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18000</umdCd><umdNm>교북동</umdNm></item><item><aptDong> </aptDong><aptNm>경희궁자이(4단지)</aptNm><aptSeq>11110-2464</aptSeq><bonbun>0126</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay>24.02.08</cdealDay><cdealType>O</cdealType><dealAmount>102,000</dealAmount><dealDay>28</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>45.879</excluUseAr><floor>16</floor><jibun>126</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><roadNm>송월길</roadNm><roadNmBonbun>00155</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100192</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18000</umdCd><umdNm>교북동</umdNm></item><item><aptDong>1</aptDong><aptNm>삼전솔하임2차</aptNm><aptSeq>11110-2322</aptSeq><bonbun>0296</bonbun><bubun>0019</bubun><buildYear>2012</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,800</dealAmount><dealDay>30</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>16.67</excluUseAr><floor>9</floor><jibun>296-19</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.22</rgstDate><roadNm>종로58가길</roadNm><roadNmBonbun>00027</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100358</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>숭인동</umdNm></item><item><aptDong>209</aptDong><aptNm>경희궁자이(2단지)</aptNm><aptSeq>11110-2445</aptSeq><bonbun>0199</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>194,000</dealAmount><dealDay>27</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>84.8359</excluUseAr><floor>8</floor><jibun>199</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.15</rgstDate><roadNm>송월길</roadNm><roadNmBonbun>00099</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100192</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17900</umdCd><umdNm>홍파동</umdNm></item><item><aptDong>102동</aptDong><aptNm>경희궁롯데캐슬</aptNm><aptSeq>11110-2519</aptSeq><bonbun>0089</bonbun><bubun>0000</bubun><buildYear>2019</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>128,000</dealAmount><dealDay>22</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>경기 부천원미구 서울 종로구</estateAgentSggNm><excluUseAr>59.6737</excluUseAr><floor>9</floor><jibun>89</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.22</rgstDate><roadNm>통일로</roadNm><roadNmBonbun>00230</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3000008</roadNmCd><roadNmSeq>00</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18700</umdCd><umdNm>무악동</umdNm></item><item><aptDong>103동</aptDong><aptNm>경희궁롯데캐슬</aptNm><aptSeq>11110-2519</aptSeq><bonbun>0089</bonbun><bubun>0000</bubun><buildYear>2019</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>150,000</dealAmount><dealDay>16</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>84.8792</excluUseAr><floor>14</floor><jibun>89</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.03.05</rgstDate><roadNm>통일로</roadNm><roadNmBonbun>00230</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3000008</roadNmCd><roadNmSeq>00</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18700</umdCd><umdNm>무악동</umdNm></item><item><aptDong>엘리시아</aptDong><aptNm>엘리시아</aptNm><aptSeq>11110-2261</aptSeq><bonbun>0066</bonbun><bubun>0001</bubun><buildYear>2009</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>114,000</dealAmount><dealDay>28</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>236.07</excluUseAr><floor>2</floor><jibun>66-1</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.12</rgstDate><roadNm>평창문화로</roadNm><roadNmBonbun>00142</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3100023</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18300</umdCd><umdNm>평창동</umdNm></item><item><aptDong>102</aptDong><aptNm>롯데낙천대</aptNm><aptSeq>11110-71</aptSeq><bonbun>0072</bonbun><bubun>0000</bubun><buildYear>2001</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>118,000</dealAmount><dealDay>20</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>110.53</excluUseAr><floor>4</floor><jibun>72</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.29</rgstDate><roadNm>평창문화로</roadNm><roadNmBonbun>00140</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3100023</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18300</umdCd><umdNm>평창동</umdNm></item><item><aptDong> </aptDong><aptNm>디팰리스</aptNm><aptSeq>11110-2539</aptSeq><bonbun>0171</bonbun><bubun>0000</bubun><buildYear>2020</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>280,000</dealAmount><dealDay>11</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 성동구</estateAgentSggNm><excluUseAr>118.749</excluUseAr><floor>16</floor><jibun>171</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.22</rgstDate><roadNm>새문안로2길</roadNm><roadNmBonbun>00010</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100157</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>12100</umdCd><umdNm>신문로2가</umdNm></item><item><aptDong>102</aptDong><aptNm>창신쌍용1</aptNm><aptSeq>11110-37</aptSeq><bonbun>0702</bonbun><bubun>0000</bubun><buildYear>1992</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>69,000</dealAmount><dealDay>8</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>79.87</excluUseAr><floor>11</floor><jibun>702</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.03.08</rgstDate><roadNm>동망산길</roadNm><roadNmBonbun>00019</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100065</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17400</umdCd><umdNm>창신동</umdNm></item><item><aptDong> </aptDong><aptNm>도시그린빌라</aptNm><aptSeq>11110-44</aptSeq><bonbun>0181</bonbun><bubun>0121</bubun><buildYear>1997</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>23,900</dealAmount><dealDay>23</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>44.4</excluUseAr><floor>6</floor><jibun>181-121</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.23</rgstDate><roadNm>숭인동1길</roadNm><roadNmBonbun>00031</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100200</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>숭인동</umdNm></item><item><aptDong>포레스트힐시티</aptDong><aptNm>포레스트힐시티</aptNm><aptSeq>11110-2440</aptSeq><bonbun>0065</bonbun><bubun>0002</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>16,000</dealAmount><dealDay>26</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>직거래</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>18.505</excluUseAr><floor>12</floor><jibun>65-2</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.05</rgstDate><roadNm>대학로</roadNm><roadNmBonbun>00033</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3100002</roadNmCd><roadNmSeq>00</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>16200</umdCd><umdNm>효제동</umdNm></item><item><aptDong> </aptDong><aptNm>종로중흥S클래스</aptNm><aptSeq>11110-2339</aptSeq><bonbun>0202</bonbun><bubun>0003</bubun><buildYear>2013</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,500</dealAmount><dealDay>4</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>직거래</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>17.811</excluUseAr><floor>11</floor><jibun>202-3</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.29</rgstDate><roadNm>종로66길</roadNm><roadNmBonbun>00028</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100372</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>숭인동</umdNm></item><item><aptDong>307</aptDong><aptNm>경희궁자이(3단지)</aptNm><aptSeq>11110-2446</aptSeq><bonbun>0233</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>148,000</dealAmount><dealDay>17</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>59.7547</excluUseAr><floor>4</floor><jibun>233</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.26</rgstDate><roadNm>경교장길</roadNm><roadNmBonbun>00035</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100002</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17700</umdCd><umdNm>평동</umdNm></item><item><aptDong>1</aptDong><aptNm>종로유케이201</aptNm><aptSeq>11110-2334</aptSeq><bonbun>0201</bonbun><bubun>0011</bubun><buildYear>2013</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,000</dealAmount><dealDay>24</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>직거래</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>12.08</excluUseAr><floor>12</floor><jibun>201-11</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.27</rgstDate><roadNm>난계로29길</roadNm><roadNmBonbun>00033</roadNmBonbun><roadNmBubun>00004</roadNmBubun><roadNmCd>4100030</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>숭인동</umdNm></item><item><aptDong>102</aptDong><aptNm>창신쌍용1</aptNm><aptSeq>11110-37</aptSeq><bonbun>0702</bonbun><bubun>0000</bubun><buildYear>1992</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>70,000</dealAmount><dealDay>2</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>79.87</excluUseAr><floor>10</floor><jibun>702</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.12</rgstDate><roadNm>동망산길</roadNm><roadNmBonbun>00019</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100065</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17400</umdCd><umdNm>창신동</umdNm></item><item><aptDong>104</aptDong><aptNm>광화문스페이스본(101동~105동)</aptNm><aptSeq>11110-2203</aptSeq><bonbun>0009</bonbun><bubun>0000</bubun><buildYear>2008</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>179,000</dealAmount><dealDay>2</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>151.81</excluUseAr><floor>11</floor><jibun>9</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.01</rgstDate><roadNm>사직로8길</roadNm><roadNmBonbun>00004</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100135</roadNmCd><roadNmSeq>03</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>11500</umdCd><umdNm>사직동</umdNm></item><item><aptDong>1</aptDong><aptNm>종로유케이201</aptNm><aptSeq>11110-2334</aptSeq><bonbun>0201</bonbun><bubun>0011</bubun><buildYear>2013</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,400</dealAmount><dealDay>19</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>직거래</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>12.09</excluUseAr><floor>9</floor><jibun>201-11</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.20</rgstDate><roadNm>난계로29길</roadNm><roadNmBonbun>00033</roadNmBonbun><roadNmBubun>00004</roadNmBubun><roadNmCd>4100030</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>숭인동</umdNm></item><item><aptDong> </aptDong><aptNm>두레엘리시안</aptNm><aptSeq>11110-2175</aptSeq><bonbun>0174</bonbun><bubun>0001</bubun><buildYear>2007</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>90,000</dealAmount><dealDay>1</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>직거래</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>84.74</excluUseAr><floor>2</floor><jibun>174-1</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.20</rgstDate><roadNm>필운대로2길</roadNm><roadNmBonbun>00002</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100525</roadNmCd><roadNmSeq>03</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>11300</umdCd><umdNm>필운동</umdNm></item><item><aptDong>105</aptDong><aptNm>종로청계힐스테이트</aptNm><aptSeq>11110-2234</aptSeq><bonbun>0766</bonbun><bubun>0000</bubun><buildYear>2009</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>98,500</dealAmount><dealDay>1</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>84.9478</excluUseAr><floor>9</floor><jibun>766</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.04.01</rgstDate><roadNm>숭인동길</roadNm><roadNmBonbun>00021</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100204</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>숭인동</umdNm></item></items><numOfRows>100</numOfRows><pageNo>1</pageNo><totalCount>20</totalCount></body></response>

In [4]:
# response.content

b'<?xml version="1.0" encoding="utf-8" standalone="yes"?><response><header><resultCode>000</resultCode><resultMsg>OK</resultMsg></header><body><items><item><aptDong>402</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xec\x9e\x90\xec\x9d\xb4(4\xeb\x8b\xa8\xec\xa7\x80)</aptNm><aptSeq>11110-2464</aptSeq><bonbun>0126</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>102,000</dealAmount><dealDay>26</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>45.879</excluUseAr><floor>16</floor><jibun>126</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.08</rgstDate><roadNm>\xec\x86\xa1\xec\x9b\x94\xea\xb8\xb8</roadNm><roadNmBonbun>00155</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100192</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18000</umdCd><umdNm>\xea\xb5\x90\xeb\xb6\x81\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xec\x9e\x90\xec\x9d\xb4(4\xeb\x8b\xa8\xec\xa7\x80)</aptNm><aptSeq>11110-2464</aptSeq><bonbun>0126</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay>24.02.08</cdealDay><cdealType>O</cdealType><dealAmount>102,000</dealAmount><dealDay>28</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>45.879</excluUseAr><floor>16</floor><jibun>126</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><roadNm>\xec\x86\xa1\xec\x9b\x94\xea\xb8\xb8</roadNm><roadNmBonbun>00155</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100192</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18000</umdCd><umdNm>\xea\xb5\x90\xeb\xb6\x81\xeb\x8f\x99</umdNm></item><item><aptDong>1</aptDong><aptNm>\xec\x82\xbc\xec\xa0\x84\xec\x86\x94\xed\x95\x98\xec\x9e\x842\xec\xb0\xa8</aptNm><aptSeq>11110-2322</aptSeq><bonbun>0296</bonbun><bubun>0019</bubun><buildYear>2012</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,800</dealAmount><dealDay>30</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>16.67</excluUseAr><floor>9</floor><jibun>296-19</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.22</rgstDate><roadNm>\xec\xa2\x85\xeb\xa1\x9c58\xea\xb0\x80\xea\xb8\xb8</roadNm><roadNmBonbun>00027</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100358</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong>209</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xec\x9e\x90\xec\x9d\xb4(2\xeb\x8b\xa8\xec\xa7\x80)</aptNm><aptSeq>11110-2445</aptSeq><bonbun>0199</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>194,000</dealAmount><dealDay>27</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>84.8359</excluUseAr><floor>8</floor><jibun>199</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.15</rgstDate><roadNm>\xec\x86\xa1\xec\x9b\x94\xea\xb8\xb8</roadNm><roadNmBonbun>00099</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100192</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17900</umdCd><umdNm>\xed\x99\x8d\xed\x8c\x8c\xeb\x8f\x99</umdNm></item><item><aptDong>102\xeb\x8f\x99</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xeb\xa1\xaf\xeb\x8d\xb0\xec\xba\x90\xec\x8a\xac</aptNm><aptSeq>11110-2519</aptSeq><bonbun>0089</bonbun><bubun>0000</bubun><buildYear>2019</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>128,000</dealAmount><dealDay>22</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xea\xb2\xbd\xea\xb8\xb0 \xeb\xb6\x80\xec\xb2\x9c\xec\x9b\x90\xeb\xaf\xb8\xea\xb5\xac \xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>59.6737</excluUseAr><floor>9</floor><jibun>89</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.22</rgstDate><roadNm>\xed\x86\xb5\xec\x9d\xbc\xeb\xa1\x9c</roadNm><roadNmBonbun>00230</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3000008</roadNmCd><roadNmSeq>00</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18700</umdCd><umdNm>\xeb\xac\xb4\xec\x95\x85\xeb\x8f\x99</umdNm></item><item><aptDong>103\xeb\x8f\x99</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xeb\xa1\xaf\xeb\x8d\xb0\xec\xba\x90\xec\x8a\xac</aptNm><aptSeq>11110-2519</aptSeq><bonbun>0089</bonbun><bubun>0000</bubun><buildYear>2019</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>150,000</dealAmount><dealDay>16</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>84.8792</excluUseAr><floor>14</floor><jibun>89</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.03.05</rgstDate><roadNm>\xed\x86\xb5\xec\x9d\xbc\xeb\xa1\x9c</roadNm><roadNmBonbun>00230</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3000008</roadNmCd><roadNmSeq>00</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18700</umdCd><umdNm>\xeb\xac\xb4\xec\x95\x85\xeb\x8f\x99</umdNm></item><item><aptDong>\xec\x97\x98\xeb\xa6\xac\xec\x8b\x9c\xec\x95\x84</aptDong><aptNm>\xec\x97\x98\xeb\xa6\xac\xec\x8b\x9c\xec\x95\x84</aptNm><aptSeq>11110-2261</aptSeq><bonbun>0066</bonbun><bubun>0001</bubun><buildYear>2009</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>114,000</dealAmount><dealDay>28</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>236.07</excluUseAr><floor>2</floor><jibun>66-1</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.12</rgstDate><roadNm>\xed\x8f\x89\xec\xb0\xbd\xeb\xac\xb8\xed\x99\x94\xeb\xa1\x9c</roadNm><roadNmBonbun>00142</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3100023</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18300</umdCd><umdNm>\xed\x8f\x89\xec\xb0\xbd\xeb\x8f\x99</umdNm></item><item><aptDong>102</aptDong><aptNm>\xeb\xa1\xaf\xeb\x8d\xb0\xeb\x82\x99\xec\xb2\x9c\xeb\x8c\x80</aptNm><aptSeq>11110-71</aptSeq><bonbun>0072</bonbun><bubun>0000</bubun><buildYear>2001</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>118,000</dealAmount><dealDay>20</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>110.53</excluUseAr><floor>4</floor><jibun>72</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.29</rgstDate><roadNm>\xed\x8f\x89\xec\xb0\xbd\xeb\xac\xb8\xed\x99\x94\xeb\xa1\x9c</roadNm><roadNmBonbun>00140</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3100023</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>18300</umdCd><umdNm>\xed\x8f\x89\xec\xb0\xbd\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xeb\x94\x94\xed\x8c\xb0\xeb\xa6\xac\xec\x8a\xa4</aptNm><aptSeq>11110-2539</aptSeq><bonbun>0171</bonbun><bubun>0000</bubun><buildYear>2020</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>280,000</dealAmount><dealDay>11</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\x84\xb1\xeb\x8f\x99\xea\xb5\xac</estateAgentSggNm><excluUseAr>118.749</excluUseAr><floor>16</floor><jibun>171</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.22</rgstDate><roadNm>\xec\x83\x88\xeb\xac\xb8\xec\x95\x88\xeb\xa1\x9c2\xea\xb8\xb8</roadNm><roadNmBonbun>00010</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100157</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>12100</umdCd><umdNm>\xec\x8b\xa0\xeb\xac\xb8\xeb\xa1\x9c2\xea\xb0\x80</umdNm></item><item><aptDong>102</aptDong><aptNm>\xec\xb0\xbd\xec\x8b\xa0\xec\x8c\x8d\xec\x9a\xa91</aptNm><aptSeq>11110-37</aptSeq><bonbun>0702</bonbun><bubun>0000</bubun><buildYear>1992</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>69,000</dealAmount><dealDay>8</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>79.87</excluUseAr><floor>11</floor><jibun>702</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.03.08</rgstDate><roadNm>\xeb\x8f\x99\xeb\xa7\x9d\xec\x82\xb0\xea\xb8\xb8</roadNm><roadNmBonbun>00019</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100065</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17400</umdCd><umdNm>\xec\xb0\xbd\xec\x8b\xa0\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xeb\x8f\x84\xec\x8b\x9c\xea\xb7\xb8\xeb\xa6\xb0\xeb\xb9\x8c\xeb\x9d\xbc</aptNm><aptSeq>11110-44</aptSeq><bonbun>0181</bonbun><bubun>0121</bubun><buildYear>1997</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>23,900</dealAmount><dealDay>23</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>44.4</excluUseAr><floor>6</floor><jibun>181-121</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.23</rgstDate><roadNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x991\xea\xb8\xb8</roadNm><roadNmBonbun>00031</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100200</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong>\xed\x8f\xac\xeb\xa0\x88\xec\x8a\xa4\xed\x8a\xb8\xed\x9e\x90\xec\x8b\x9c\xed\x8b\xb0</aptDong><aptNm>\xed\x8f\xac\xeb\xa0\x88\xec\x8a\xa4\xed\x8a\xb8\xed\x9e\x90\xec\x8b\x9c\xed\x8b\xb0</aptNm><aptSeq>11110-2440</aptSeq><bonbun>0065</bonbun><bubun>0002</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>16,000</dealAmount><dealDay>26</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>18.505</excluUseAr><floor>12</floor><jibun>65-2</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.05</rgstDate><roadNm>\xeb\x8c\x80\xed\x95\x99\xeb\xa1\x9c</roadNm><roadNmBonbun>00033</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>3100002</roadNmCd><roadNmSeq>00</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>16200</umdCd><umdNm>\xed\x9a\xa8\xec\xa0\x9c\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xec\xa2\x85\xeb\xa1\x9c\xec\xa4\x91\xed\x9d\xa5S\xed\x81\xb4\xeb\x9e\x98\xec\x8a\xa4</aptNm><aptSeq>11110-2339</aptSeq><bonbun>0202</bonbun><bubun>0003</bubun><buildYear>2013</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,500</dealAmount><dealDay>4</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>17.811</excluUseAr><floor>11</floor><jibun>202-3</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.29</rgstDate><roadNm>\xec\xa2\x85\xeb\xa1\x9c66\xea\xb8\xb8</roadNm><roadNmBonbun>00028</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100372</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong>307</aptDong><aptNm>\xea\xb2\xbd\xed\x9d\xac\xea\xb6\x81\xec\x9e\x90\xec\x9d\xb4(3\xeb\x8b\xa8\xec\xa7\x80)</aptNm><aptSeq>11110-2446</aptSeq><bonbun>0233</bonbun><bubun>0000</bubun><buildYear>2017</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>148,000</dealAmount><dealDay>17</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>59.7547</excluUseAr><floor>4</floor><jibun>233</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.26</rgstDate><roadNm>\xea\xb2\xbd\xea\xb5\x90\xec\x9e\xa5\xea\xb8\xb8</roadNm><roadNmBonbun>00035</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100002</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd> </roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17700</umdCd><umdNm>\xed\x8f\x89\xeb\x8f\x99</umdNm></item><item><aptDong>1</aptDong><aptNm>\xec\xa2\x85\xeb\xa1\x9c\xec\x9c\xa0\xec\xbc\x80\xec\x9d\xb4201</aptNm><aptSeq>11110-2334</aptSeq><bonbun>0201</bonbun><bubun>0011</bubun><buildYear>2013</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,000</dealAmount><dealDay>24</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>12.08</excluUseAr><floor>12</floor><jibun>201-11</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.27</rgstDate><roadNm>\xeb\x82\x9c\xea\xb3\x84\xeb\xa1\x9c29\xea\xb8\xb8</roadNm><roadNmBonbun>00033</roadNmBonbun><roadNmBubun>00004</roadNmBubun><roadNmCd>4100030</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong>102</aptDong><aptNm>\xec\xb0\xbd\xec\x8b\xa0\xec\x8c\x8d\xec\x9a\xa91</aptNm><aptSeq>11110-37</aptSeq><bonbun>0702</bonbun><bubun>0000</bubun><buildYear>1992</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>70,000</dealAmount><dealDay>2</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>79.87</excluUseAr><floor>10</floor><jibun>702</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.01.12</rgstDate><roadNm>\xeb\x8f\x99\xeb\xa7\x9d\xec\x82\xb0\xea\xb8\xb8</roadNm><roadNmBonbun>00019</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100065</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17400</umdCd><umdNm>\xec\xb0\xbd\xec\x8b\xa0\xeb\x8f\x99</umdNm></item><item><aptDong>104</aptDong><aptNm>\xea\xb4\x91\xed\x99\x94\xeb\xac\xb8\xec\x8a\xa4\xed\x8e\x98\xec\x9d\xb4\xec\x8a\xa4\xeb\xb3\xb8(101\xeb\x8f\x99~105\xeb\x8f\x99)</aptNm><aptSeq>11110-2203</aptSeq><bonbun>0009</bonbun><bubun>0000</bubun><buildYear>2008</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>179,000</dealAmount><dealDay>2</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa4\x91\xea\xb0\x9c\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm>\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac</estateAgentSggNm><excluUseAr>151.81</excluUseAr><floor>11</floor><jibun>9</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.02.01</rgstDate><roadNm>\xec\x82\xac\xec\xa7\x81\xeb\xa1\x9c8\xea\xb8\xb8</roadNm><roadNmBonbun>00004</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100135</roadNmCd><roadNmSeq>03</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>11500</umdCd><umdNm>\xec\x82\xac\xec\xa7\x81\xeb\x8f\x99</umdNm></item><item><aptDong>1</aptDong><aptNm>\xec\xa2\x85\xeb\xa1\x9c\xec\x9c\xa0\xec\xbc\x80\xec\x9d\xb4201</aptNm><aptSeq>11110-2334</aptSeq><bonbun>0201</bonbun><bubun>0011</bubun><buildYear>2013</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>10,400</dealAmount><dealDay>19</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>12.09</excluUseAr><floor>9</floor><jibun>201-11</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.20</rgstDate><roadNm>\xeb\x82\x9c\xea\xb3\x84\xeb\xa1\x9c29\xea\xb8\xb8</roadNm><roadNmBonbun>00033</roadNmBonbun><roadNmBubun>00004</roadNmBubun><roadNmCd>4100030</roadNmCd><roadNmSeq>01</roadNmSeq><roadNmSggCd>11110</roadNmSggCd><roadNmbCd>0</roadNmbCd><sggCd>11110</sggCd><slerGbn> </slerGbn><umdCd>17500</umdCd><umdNm>\xec\x88\xad\xec\x9d\xb8\xeb\x8f\x99</umdNm></item><item><aptDong> </aptDong><aptNm>\xeb\x91\x90\xeb\xa0\x88\xec\x97\x98\xeb\xa6\xac\xec\x8b\x9c\xec\x95\x88</aptNm><aptSeq>11110-2175</aptSeq><bonbun>0174</bonbun><bubun>0001</bubun><buildYear>2007</buildYear><buyerGbn> </buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>90,000</dealAmount><dealDay>1</dealDay><dealMonth>12</dealMonth><dealYear>2023</dealYear><dealingGbn>\xec\xa7\x81\xea\xb1\xb0\xeb\x9e\x98</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>84.74</excluUseAr><floor>2</floor><jibun>174-1</jibun><landCd>1</landCd><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>23.12.20</rgstDate><roadNm>\xed\x95\x84\xec\x9a\xb4\xeb\x8c\x80\xeb\xa1\x9c2\xea\xb8\xb8</roadNm><roadNmBonbun>00002</roadNmBonbun><roadNmBubun>00000</roadNmBubun><roadNmCd>4100525</roadNmCd><roadNmSeq>03</roadNmSeq><roadNmSggCd>11110</road

In [5]:
df_api.shape

(20, 6)

In [32]:
df_api.head(3)

  Transaction_Date dealAmount excluUseAr floor buildYear Location
0         20231226    102,000     45.879    16      2017       서울
1         20231228    102,000     45.879    16      2017       대구
2         20231230     10,800      16.67     9      2012       대구

In [5]:
df_api.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_Date  20 non-null     object
 1   dealAmount        20 non-null     object
 2   excluUseAr        20 non-null     object
 3   floor             20 non-null     object
 4   buildYear         20 non-null     object
 5   Location          20 non-null     object
dtypes: object(6)
memory usage: 1.1+ KB

In [31]:
df_api.columns

Index(['Transaction_Date', 'dealAmount', 'excluUseAr', 'floor', 'buildYear',
       'Location'],
      dtype='object')

In [6]:
df_api = pd.read_csv('df_api.csv').drop(columns=['Unnamed: 0'])
df_api.head(3)

,Unnamed: 0,Transaction_Date,dealAmount,excluUseAr,floor,buildYear,Location
0,0,20231226,"102,000",45.879,16,2017,서울
1,1,20231228,"102,000",45.879,16,2017,대구
2,2,20231230,"10,800",16.670,9,2012,대구

In [21]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

df_api = pd.read_csv('df_api.csv').drop(columns=['Unnamed: 0'])

print("=== 원본 데이터 ===\n", df_api, "\n")

df_api['floor'] = pd.to_numeric(df_api['floor'])
df_api['buildYear'] = pd.to_numeric(df_api['buildYear'])
df_api['dealAmount'] = df_api['dealAmount'].str.replace(',','').astype(int)



## 1. 결측치 처리 (Imputation)
# Floor(층)는 중앙값으로, Built_Year(건축년도)는 최빈값으로 채웁니다.
df_api['floor'] = df_api['floor'].fillna(df_api['floor'].median())
# 최빈값(mode)은 Series를 반환하므로 [0]으로 첫 번째 값을 추출합니다.
df_api['buildYear'] = df_api['buildYear'].fillna(df_api['buildYear'].mode()[0])
print("=== 결측치 처리후 ===\n", df_api, "\n")

## 2. 범주형 변수 인코딩 (Categorical Encoding)
# Location(지역)은 순서가 없는 명목형 데이터이므로 원-핫 인코딩(One-Hot Encoding)을 적용합니다.
df = pd.get_dummies(df_api, columns=['Location'], drop_first=True, dtype=int)
print("=== 범주형 변수 인코딩 처리후 ===\n", df, "\n")

## 3. 수치형 변수 스케일링 (Feature Scaling)
# Area(면적) 변수를 모델이 잘 학습하도록 평균 0, 표준편차 1인 표준화(Standardization)를 진행합니다.
scaler = StandardScaler()
df['Area_Scaled'] = scaler.fit_transform(df[['excluUseAr']])
print("=== 수치형 변수 스케일링 처리후 ===\n", df, "\n")

## 4. 데이터 변환 및 구간화 (Transformation & Binning)
# 거래금액(Price)은 단위가 크고 우측으로 꼬리가 긴 분포를 가지기 쉬우므로 로그 변환을 합니다.
df['Price_Log'] = np.log1p(df_api['dealAmount'])

# 건축년도(Built_Year)를 연대별로 묶어 범주형 변수로 만듭니다.
bins = [1900, 1999, 2009, 2029]
labels = ['1990s_and_befor', '2000s', '2010s_and_after']
df['Built_Decade'] = pd.cut(df['buildYear'], bins=bins, labels=labels)
print("=== 수치형 변수 스케일링 처리 후 ===\n", df, "\n")

## 5. 파생 변수 생성 (Feature Creation)
# Transaction_Date에서 연/월 파생 변수를 추출합니다.
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])
df['Trans_Year'] = df['Transaction_Date'].dt.year
df['Trans_Month'] = df['Transaction_Date'].dt.month

# 현재 시점을 기준으로 건물의 나이(Age_of_Building)라는 새로운 핵심 피처를 만듭니다.
df['Age_of_Building'] = 2026 - df['buildYear']
print("=== 파생 변수 생성 처리 후 ===\n", df, "\n")
df_api.head()

=== 원본 데이터 ===
     Transaction_Date dealAmount  excluUseAr  floor  buildYear Location
0           20231226    102,000     45.8790     16       2017       서울
1           20231228    102,000     45.8790     16       2017       대구
2           20231230     10,800     16.6700      9       2012       대구
3           20231227    194,000     84.8359      8       2017       대전
4           20231222    128,000     59.6737      9       2019       대전
5           20231216    150,000     84.8792     14       2019       제주
6           20231228    114,000    236.0700      2       2009       서울
7           20231220    118,000    110.5300      4       2001       대구
8           20231211    280,000    118.7490     16       2020       광주
9            2023128     69,000     79.8700     11       1992       서울
10          20231223     23,900     44.4000      6       1997       대전
11          20231226     16,000     18.5050     12       2017       제주
12           2023124     10,500     17.8110     11       2013       대구
13          20231217    148,000     59.7547      4       2017       대구
14          20231224     10,000     12.0800     12       2013       대구
15           2023122     70,000     79.8700     10       1992       대구
16           2023122    179,000    151.8100     11       2008       대전
17          20231219     10,400     12.0900      9       2013       서울
18           2023121     90,000     84.7400      2       2007       제주
19           2023121     98,500     84.9478      9       2009       대전

=== 결측치 처리후 ===
     Transaction_Date  dealAmount  excluUseAr  floor  buildYear Location
0           20231226      102000     45.8790     16       2017       서울
1           20231228      102000     45.8790     16       2017       대구
2           20231230       10800     16.6700      9       2012       대구
3           20231227      194000     84.8359      8       2017       대전
4           20231222      128000     59.6737      9       2019       대전
5           20231216      150000     84.8792     14       2019       제주
6           20231228      114000    236.0700      2       2009       서울
7           20231220      118000    110.5300      4       2001       대구
8           20231211      280000    118.7490     16       2020       광주
9            2023128       69000     79.8700     11       1992       서울
10          20231223       23900     44.4000      6       1997       대전
11          20231226       16000     18.5050     12       2017       제주
12           2023124       10500     17.8110     11       2013       대구
13          20231217      148000     59.7547      4       2017       대구
14          20231224       10000     12.0800     12       2013       대구
15           2023122       70000     79.8700     10       1992       대구
16           2023122      179000    151.8100     11       2008       대전
17          20231219       10400     12.0900      9       2013       서울
18           2023121       90000     84.7400      2       2007       제주
19           2023121       98500     84.9478      9       2009       대전

=== 범주형 변수 인코딩 처리후 ===
     Transaction_Date  dealAmount  excluUseAr  floor  buildYear  Location_대구  \
0           20231226      102000     45.8790     16       2017            0
1           20231228      102000     45.8790     16       2017            1
2           20231230       10800     16.6700      9       2012            1
3           20231227      194000     84.8359      8       2017            0
4           20231222      128000     59.6737      9       2019            0
5           20231216      150000     84.8792     14       2019            0
6           20231228      114000    236.0700      2       2009            0
7           20231220      118000    110.5300      4       2001            1
8           20231211      280000    118.7490     16       2020            0
9            2023128       69000     79.8700     11       1992            0
10          20231223       23900     44.4000      6       1997            0
11          20231226       16000     18.5050     12       2017            0
12           2023124       10500     17.8110     11       2013            1
13          20231217      148000     59.7547      4       2017            1
14          20231224       10000     12.0800     12       2013            1
15           2023122       70000     79.8700     10       1992            1
16           2023122      179000    151.8100     11       2008            0
17          20231219       10400     12.0900      9       2013            0
18           2023121       90000     84.7400      2       2007            0
19           2023121       98500     84.9478      9       2009            0

    Location_대전  Location_서울  Location_제주
0             0            1            0
1             0            0            0
2             0            0            0
3             1            0            0
4             1            0            0
5             0            0            1
6             0            1            0
7             0            0            0
8             0            0            0
9             0            1            0
10            1            0            0
11            0            0            1
12            0            0            0
13            0            0            0
14            0            0            0
15            0            0            0
16            1            0            0
17            0            1            0
18            0            0            1
19            1            0            0

=== 수치형 변수 스케일링 처리후 ===
     Transaction_Date  dealAmount  excluUseAr  floor  buildYear  Location_대구  \
0           20231226      102000     45.8790     16       2017            0
1           20231228      102000     45.8790     16       2017            1
2           20231230       10800     16.6700      9       2012            1
3           20231227      194000     84.8359      8       2017            0
4           20231222      128000     59.6737      9       2019            0
5           20231216      150000     84.8792     14       2019            0
6           20231228      114000    236.0700      2       2009            0
7           20231220      118000    110.5300      4       2001            1
8           20231211      280000    118.7490     16       2020            0
9            2023128       69000     79.8700     11       1992            0
10          20231223       23900     44.4000      6       1997            0
11          20231226       16000     18.5050     12       2017            0
12           2023124       10500     17.8110     11       2013            1
13          20231217      148000     59.7547      4       2017            1
14          20231224       10000     12.0800     12       2013            1
15           2023122       70000     79.8700     10       1992            1
16           2023122      179000    151.8100     11       2008            0
17          20231219       10400     12.0900      9       2013            0
18           2023121       90000     84.7400      2       2007            0
19           2023121       98500     84.9478      9       2009            0

    Location_대전  Location_서울  Location_제주  Area_Scaled
0             0            1            0    -0.501263
1             0            0            0    -0.501263
2             0            0            0    -1.052247
3             1            0            0     0.233599
4             1            0            0    -0.241047
5             0            0            1     0.234416
6             0            1            0     3.086402
7             0            0            0     0.718280
8             0            0            0     0.873319
9             0            1            0     0.139925
10            1            0            0    -0.529163
11            0            0            1    -1.017632
12            0            0            0    -1.030724
13            0            0            0    -0.239519
14            0            0            0    -1.138830
15            0            0            0     0.139925
16            1            0            0     1.496964
17            0            1            0    -1.138642
18            0            0            1     0.231790
19            1            0            0     0.235710

=== 수치형 변수 스케일링 처리 후 ===
     Transaction_Date  dealAmount  excluUseAr  floor  buildYear  Location_대구  \
0           20231226      102000     45.8790     16       2017            0
1           20231228      102000     45.8790     16       2017            1
2           20231230       10800     16.6700      9       2012            1
3           20231227      194000     84.8359      8       2017            0
4           20231222      128000     59.6737      9       2019            0
5           20231216      150000     84.8792     14       2019            0
6           20231228      114000    236.0700      2       2009            0
7           20231220      118000    110.5300      4       2001            1
8           20231211      280000    118.7490     16       2020            0
9            2023128       69000     79.8700     11       1992            0
10          20231223       23900     44.4000      6       1997            0
11          20231226       16000     18.5050     12       2017            0
12           2023124       10500     17.8110     11       2013            1
13          20231217      148000     59.7547      4       2017            1
14          20231224       10000     12.0800     12       2013            1
15           2023122       70000     79.8700     10       1992            1
16           2023122      179000    151.8100     11       2008            0
17          20231219       10400     12.0900      9       2013            0
18           2023121       90000     84.7400      2       2007            0
19           2023121       98500     84.9478      9       2009            0

    Location_대전  Location_서울  Location_제주  Area_Scaled  Price_Log  \
0             0            1            0    -0.501263  11.532738
1             0            0            0    -0.501263  11.532738
2             0            0            0    -1.052247   9.287394
3             1            0            0     0.233599  12.175619
4             1            0            0    -0.241047  11.759793
5             0            0            1     0.234416  11.918397
6             0            1            0     3.086402  11.643962
7             0            0            0     0.718280  11.678448
8             0            0            0     0.873319  12.542548
9             0            1            0     0.139925  11.141876
10            1            0            0    -0.529163  10.081676
11            0            0            1    -1.017632   9.680406
12            0            0            0    -1.030724   9.259226
13            0            0            0    -0.239519  11.904974
14            0            0            0    -1.138830   9.210440
15            0            0            0     0.139925  11.156265
16            1            0            0     1.496964  12.095147
17            0            1            0    -1.138642   9.249657
18            0            0            1     0.231790  11.407576
19            1            0            0     0.235710  11.497822

       Built_Decade
0   2010s_and_after
1   2010s_and_after
2   2010s_and_after
3   2010s_and_after
4   2010s_and_after
5   2010s_and_after
6             2000s
7             2000s
8   2010s_and_after
9   1990s_and_befor
10  1990s_and_befor
11  2010s_and_after
12  2010s_and_after
13  2010s_and_after
14  2010s_and_after
15  1990s_and_befor
16            2000s
17  2010s_and_after
18            2000s
19            2000s

=== 파생 변수 생성 처리 후 ===
                 Transaction_Date  dealAmount  excluUseAr  floor  buildYear  \
0  1970-01-01 00:00:00.020231226      102000     45.8790     16       2017
1  1970-01-01 00:00:00.020231228      102000     45.8790     16       2017
2  1970-01-01 00:00:00.020231230       10800     16.6700      9       2012
3  1970-01-01 00:00:00.020231227      194000     84.8359      8       2017
4  1970-01-01 00:00:00.020231222      128000     59.6737      9       2019
5  1970-01-01 00:00:00.020231216      150000     84.8792     14       2019
6  1970-01-01 00:00:00.020231228      114000    236.0700      2       2009
7  1970-01-01 00:00:00.020231220      118000    110.5300      4       2001
8  1970-01-01 00:00:00.020231211      280000    118.7490     16       2020
9  1970-01-01 00:00:00.002023128       69000     79.8700     11       1992
10 1970-01-01 00:00:00.020231223       23900     44.4000      6       1997
11 1970-01-01 00:00:00.020231226       16000     18.5050     12       2017
12 1970-01-01 00:00:00.002023124       10500     17.8110     11       2013
13 1970-01-01 00:00:00.020231217      148000     59.7547      4       2017
14 1970-01-01 00:00:00.020231224       10000     12.0800     12       2013
15 1970-01-01 00:00:00.002023122       70000     79.8700     10       1992
16 1970-01-01 00:00:00.002023122      179000    151.8100     11       2008
17 1970-01-01 00:00:00.020231219       10400     12.0900      9       2013
18 1970-01-01 00:00:00.002023121       90000     84.7400      2       2007
19 1970-01-01 00:00:00.002023121       98500     84.9478      9       2009

    Location_대구  Location_대전  Location_서울  Location_제주  Area_Scaled  \
0             0            0            1            0    -0.501263
1             1            0            0            0    -0.501263
2             1            0            0            0    -1.052247
3             0            1            0            0     0.233599
4             0            1            0            0    -0.241047
5             0            0            0            1     0.234416
6             0            0            1            0     3.086402
7             1            0            0            0     0.718280
8             0            0            0            0     0.873319
9             0            0            1            0     0.139925
10            0            1            0            0    -0.529163
11            0            0            0            1    -1.017632
12            1            0            0            0    -1.030724
13            1            0            0            0    -0.239519
14            1            0            0            0    -1.138830
15            1            0            0            0     0.139925
16            0            1            0            0     1.496964
17            0            0            1            0    -1.138642
18            0            0            0            1     0.231790
19            0            1            0            0     0.235710

    Price_Log     Built_Decade  Trans_Year  Trans_Month  Age_of_Building
0   11.532738  2010s_and_after        1970            1                9
1   11.532738  2010s_and_after        1970            1                9
2    9.287394  2010s_and_after        1970            1               14
3   12.175619  2010s_and_after        1970            1                9
4   11.759793  2010s_and_after        1970            1                7
5   11.918397  2010s_and_after        1970            1                7
6   11.643962            2000s        1970            1               17
7   11.678448            2000s        1970            1               25
8   12.542548  2010s_and_after        1970            1                6
9   11.141876  1990s_and_befor        1970            1               34
10  10.081676  1990s_and_befor        1970            1               29
11   9.680406  2010s_and_after        1970            1                9
12   9.259226  2010s_and_after        1970            1               13
13  11.904974  2010s_and_after        1970            1                9
14   9.210440  2010s_and_after        1970            1               13
15  11.156265  1990s_and_befor        1970            1               34
16  12.095147            2000s        1970            1               18
17   9.249657  2010s_and_after        1970            1               13
18  11.407576            2000s        1970            1               19
19  11.497822            2000s        1970            1               17

   Transaction_Date  dealAmount  excluUseAr  floor  buildYear Location
0          20231226      102000     45.8790     16       2017       서울
1          20231228      102000     45.8790     16       2017       대구
2          20231230       10800     16.6700      9       2012       대구
3          20231227      194000     84.8359      8       2017       대전
4          20231222      128000     59.6737      9       2019       대전

In [23]:
df

,Transaction_Date,dealAmount,excluUseAr,floor,buildYear,Location_대구,Location_대전,Location_서울,Location_제주,Area_Scaled,Price_Log,Built_Decade,Trans_Year,Trans_Month,Age_of_Building
0,1970-01-01 00:00:00.020231226,102000,45.8790,16,2017,0,0,1,0,-0.501263,11.532738,2010s_and_after,1970,1,9
1,1970-01-01 00:00:00.020231228,102000,45.8790,16,2017,1,0,0,0,-0.501263,11.532738,2010s_and_after,1970,1,9
2,1970-01-01 00:00:00.020231230,10800,16.6700,9,2012,1,0,0,0,-1.052247,9.287394,2010s_and_after,1970,1,14
3,1970-01-01 00:00:00.020231227,194000,84.8359,8,2017,0,1,0,0,0.233599,12.175619,2010s_and_after,1970,1,9
4,1970-01-01 00:00:00.020231222,128000,59.6737,9,2019,0,1,0,0,-0.241047,11.759793,2010s_and_after,1970,1,7
5,1970-01-01 00:00:00.020231216,150000,84.8792,14,2019,0,0,0,1,0.234416,11.918397,2010s_and_after,1970,1,7
6,1970-01-01 00:00:00.020231228,114000,236.0700,2,2009,0,0,1,0,3.086402,11.643962,2000s,1970,1,17
7,1970-01-01 00:00:00.020231220,118000,110.5300,4,2001,1,0,0,0,0.718280,11.678448,2000s,1970,1,25
8,1970-01-01 00:00:00.020231211,280000,118.7490,16,2020,0,0,0,0,0.873319,12.542548,2010s_and_after,1970,1,6
9,1970-01-01 00:00:00.002023128,69000,79.8700,11,1992,0,0,1,0,0.139925,11.141876,1990s_and_befor,1970,1,34
10,1970-01-01 00:00:00.020231223,23900,44.4000,6,1997,0,1,0,0,-0.529163,10.081676,1990s_and_befor,1970,1,29
11,1970-01-01 00:00:00.020231226,16000,18.5050,12,2017,0,0,0,1,-1.017632,9.680406,2010s_and_after,1970,1,9
12,1970-01-01 00:00:00.002023124,10500,17.8110,11,2013,1,0,0,0,-1.030724,9.259226,2010s_and_after,1970,1,13
13,1970-01-01 00:00:00.020231217,148000,59.7547,4,2017,1,0,0,0,-0.239519,11.904974,2010s_and_after,1970,1,9
14,1970-01-01 00:00:00.020231224,10000,12.0800,12,2013,1,0,0,0,-1.138830,9.210440,2010s_and_after,1970,1,13
15,1970-01-01 00:00:00.002023122,70000,79.8700,10,1992,1,0,0,0,0.139925,11.156265,1990s_and_befor,1970,1,34
16,1970-01-01 00:00:00.002023122,179000,151.8100,11,2008,0,1,0,0,1.496964,12.095147,2000s,1970,1,18
17,1970-01-01 00:00:00.020231219,10400,12.0900,9,2013,0,0,1,0,-1.138642,9.249657,2010s_and_after,1970,1,13
18,1970-01-01 00:00:00.002023121,90000,84.7400,2,2007,0,0,0,1,0.231790,11.407576,2000s,1970,1,19
19,1970-01-01 00:00:00.002023121,98500,84.9478,9,2009,0,1,0,0,0.235710,11.497822,2000s,1970,1,17

In [15]:
# 'Unnamed: 0'이라는 이름으로 생성된 인덱스 열 삭제하기
df_api = pd.read_csv('df_api.csv').drop(columns=['Unnamed: 0'])
df_api

    Transaction_Date  dealAmount  excluUseAr  floor  buildYear Location
0           20231226      102000     45.8790     16       2017       서울
1           20231228      102000     45.8790     16       2017       대구
2           20231230       10800     16.6700      9       2012       대구
3           20231227      194000     84.8359      8       2017       대전
4           20231222      128000     59.6737      9       2019       대전
5           20231216      150000     84.8792     14       2019       제주
6           20231228      114000    236.0700      2       2009       서울
7           20231220      118000    110.5300      4       2001       대구
8           20231211      280000    118.7490     16       2020       광주
9            2023128       69000     79.8700     11       1992       서울
10          20231223       23900     44.4000      6       1997       대전
11          20231226       16000     18.5050     12       2017       제주
12           2023124       10500     17.8110     11       2013       대구
13          20231217      148000     59.7547      4       2017       대구
14          20231224       10000     12.0800     12       2013       대구
15           2023122       70000     79.8700     10       1992       대구
16           2023122      179000    151.8100     11       2008       대전
17          20231219       10400     12.0900      9       2013       서울
18           2023121       90000     84.7400      2       2007       제주
19           2023121       98500     84.9478      9       2009       대전